import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle, ShadingType, convertInchesToTwip } from 'docx';
import { saveAs } from 'file-saver';

export async function generateWordReport(reportData: any, companyInfo: any, assessmentScore: number) {
  console.log('generateWordReport called');
  console.log('Creating document...');
  
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        // Title
        new Paragraph({
          text: "AI TRANSFORMATION",
          heading: HeadingLevel.TITLE,
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
          children: [
            new TextRun({
              text: "AI TRANSFORMATION",
              bold: true,
              size: 36,
              color: "1E40AF", // Blue
            }),
          ],
        }),
        new Paragraph({
          text: "COMPETITIVE INTELLIGENCE REPORT",
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
          children: [
            new TextRun({
              text: "COMPETITIVE INTELLIGENCE REPORT",
              bold: true,
              size: 28,
              color: "DC2626", // Red
            }),
          ],
        }),

        // Company Information Section
        new Paragraph({
          text: "COMPANY INFORMATION",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        }),
        createInfoTable([
          ["Industry", companyInfo?.industry || 'N/A'],
          ["Country", companyInfo?.country || 'N/A'],
          ["Website", companyInfo?.companyUrl || 'N/A'],
          ["Report Generated", new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })],
        ]),

        // Executive Summary
        new Paragraph({
          text: "EXECUTIVE SUMMARY",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        }),
        createInfoTable([
          ["AI Readiness Score", `${assessmentScore}%`],
          ["Risk Level", assessmentScore >= 75 ? 'Low' : assessmentScore >= 50 ? 'Medium' : 'High'],
          ["Market Size", reportData.executiveSummary?.marketSize || 'N/A'],
          ["Growth Projection", reportData.executiveSummary?.growthProjection || 'N/A'],
        ]),
        new Paragraph({
          text: reportData.executiveSummary?.globalTrends || '',
          spacing: { before: 200, after: 200 },
        }),

        // Competitive Landscape
        new Paragraph({
          text: "COMPETITIVE LANDSCAPE ANALYSIS",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
          pageBreakBefore: true,
        }),
        ...createCompetitorSections(reportData.competitorAnalysis || []),

        // Industry Leaders
        new Paragraph({
          text: "TOP AI ADOPTERS IN YOUR INDUSTRY",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
          pageBreakBefore: true,
        }),
        ...createIndustryLeadersTable(reportData.industryLeaders || []),

        // Market Opportunities
        new Paragraph({
          text: "MARKET OPPORTUNITIES",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
          pageBreakBefore: true,
        }),
        ...createOpportunitiesSection(reportData.opportunities || []),

        // Strategic Recommendations
        new Paragraph({
          text: "STRATEGIC RECOMMENDATIONS",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
          pageBreakBefore: true,
        }),
        ...createRecommendationsSection(reportData.recommendations || []),

        // Sources & References
        new Paragraph({
          text: "SOURCES & REFERENCES",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
          pageBreakBefore: true,
        }),
        ...createSourcesSection(reportData.sources || []),

        // Next Steps
        new Paragraph({
          text: "NEXT STEPS",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
          pageBreakBefore: true,
        }),
        ...createNextSteps(),

        // Footer
        new Paragraph({
          text: "For detailed implementation guidance, contact our AI transformation consultants.",
          alignment: AlignmentType.CENTER,
          spacing: { before: 400 },
          italics: true,
        }),
        new Paragraph({
          text: "Generated by AI Transformation Hub",
          alignment: AlignmentType.CENTER,
          spacing: { before: 200 },
          children: [
            new TextRun({
              text: "Generated by AI Transformation Hub",
              size: 20,
              color: "6B7280",
            }),
          ],
        }),
      ],
    }],
  });

  // Generate and download
  console.log('Converting document to blob...');
  const blob = await Packer.toBlob(doc);
  console.log('Blob created, size:', blob.size);
  
  const fileName = `AI-Transformation-Report-${companyInfo?.industry || 'Assessment'}-${new Date().toISOString().split('T')[0]}.docx`;
  console.log('Saving file as:', fileName);
  
  saveAs(blob, fileName);
  console.log('File save triggered');
}

function createInfoTable(data: string[][]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: data.map(([label, value]) => new TableRow({
      children: [
        new TableCell({
          width: { size: 30, type: WidthType.PERCENTAGE },
          shading: { fill: "F3F4F6" },
          children: [new Paragraph({
            text: label,
            bold: true,
          })],
        }),
        new TableCell({
          width: { size: 70, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ text: value })],
        }),
      ],
    })),
  });
}

function createCompetitorSections(competitors: any[]): Paragraph[] {
  const sections: Paragraph[] = [];
  
  competitors.forEach((competitor, index) => {
    sections.push(
      new Paragraph({
        text: `${index + 1}. ${competitor.name}`,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      }),
      new Paragraph({
        text: `Region: ${competitor.region} | AI Maturity: ${competitor.aiMaturity} | Threat Level: ${competitor.threatLevel}`,
        spacing: { after: 100 },
        italics: true,
      }),
      new Paragraph({
        text: competitor.description || '',
        spacing: { after: 100 },
      }),
      new Paragraph({
        text: `Key Initiatives: ${competitor.initiatives?.join(', ') || 'N/A'}`,
        spacing: { after: 200 },
      })
    );
  });
  
  return sections;
}

function createIndustryLeadersTable(leaders: any[]): Paragraph[] {
  const sections: Paragraph[] = [];
  
  leaders.forEach((leader, index) => {
    sections.push(
      new Paragraph({
        text: `${index + 1}. ${leader.name}`,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      }),
      new Paragraph({
        text: `AI Investment: ${leader.aiInvestment} | ROI Increase: ${leader.roiIncrease} | Efficiency Gain: ${leader.efficiencyGain}`,
        spacing: { after: 100 },
      }),
      new Paragraph({
        text: `Key Initiatives: ${leader.initiatives?.join(', ') || 'N/A'}`,
        spacing: { after: 200 },
      })
    );
  });
  
  return sections;
}

function createOpportunitiesSection(opportunities: any[]): Paragraph[] {
  const sections: Paragraph[] = [];
  
  opportunities.forEach((opp, index) => {
    sections.push(
      new Paragraph({
        text: `${index + 1}. ${opp.title}`,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      }),
      new Paragraph({
        text: opp.description || '',
        spacing: { after: 100 },
      }),
      new Paragraph({
        text: `Impact: ${opp.impact} | Timeline: ${opp.timeline} | Investment: ${opp.investment}`,
        spacing: { after: 200 },
        italics: true,
      })
    );
    
    if (opp.smmeExample) {
      sections.push(
        new Paragraph({
          text: `Example: ${opp.smmeExample}`,
          spacing: { after: 200 },
          shading: { fill: "EFF6FF" },
        })
      );
    }
  });
  
  return sections;
}

function createRecommendationsSection(recommendations: any[]): Paragraph[] {
  const sections: Paragraph[] = [];
  
  recommendations.forEach((rec, index) => {
    sections.push(
      new Paragraph({
        text: `${index + 1}. ${rec.title}`,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      }),
      new Paragraph({
        text: rec.description || '',
        spacing: { after: 100 },
      }),
      new Paragraph({
        text: `Priority: ${rec.priority} | Expected ROI: ${rec.expectedRoi} | Timeline: ${rec.timeline}`,
        spacing: { after: 200 },
        italics: true,
      })
    );
  });
  
  return sections;
}

function createSourcesSection(sources: any[]): Paragraph[] {
  const sections: Paragraph[] = [];
  
  sources.forEach((source, index) => {
    sections.push(
      new Paragraph({
        text: `[${index + 1}] ${source.title}`,
        spacing: { before: 200, after: 50 },
        bold: true,
      }),
      new Paragraph({
        text: `${source.organization} • ${source.year}`,
        spacing: { after: 50 },
        italics: true,
      }),
      new Paragraph({
        text: `"${source.keyFinding}"`,
        spacing: { after: 100 },
      })
    );
    
    if (source.url && source.url !== '#') {
      sections.push(
        new Paragraph({
          text: `URL: ${source.url}`,
          spacing: { after: 200 },
          children: [
            new TextRun({
              text: source.url,
              color: "2563EB",
            }),
          ],
        })
      );
    }
  });
  
  return sections;
}

function createNextSteps(): Paragraph[] {
  const steps = [
    "Review competitive analysis and identify gaps in your AI capabilities",
    "Prioritize high-impact AI opportunities based on your readiness score",
    "Allocate budget for pilot projects in key business areas",
    "Form cross-functional AI task force with executive sponsorship",
    "Establish AI governance framework and ethical guidelines",
    "Schedule consultation for detailed implementation guidance",
  ];
  
  return steps.map((step, index) => new Paragraph({
    text: `${index + 1}. ${step}`,
    spacing: { after: 100 },
    numbering: {
      reference: "default-numbering",
      level: 0,
    },
  }));
}
